[programs.localnet]
first = "5Zt39d9oMSDK6JgUMpbXvuMqZ3EdAhMqHK2mCgRpPeBL"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/developer/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
