[programs.localnet]
first = "HHJgVhndgFHUF6BrtnFuSJir4BVLt4TSb6mEzPivsxDJ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/developer/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
